### ISSUE TITLE
Permission denied, couldn't send a pull request

### ISSUE THREAD

**Issue by HananeAlSamrout** [react-community/native-directory#135]
i am trying to send a pull request from my branch to the master branch, it is giving me 

> fatal: unable to access 'https://github.com/react-community/native-directory.git/': The requested URL returned error: 403

**Comment by nicknovitski** [comment]
Pull requests are created via github's site or api, not with git.  See [their help article on the subject](https://help.github.com/articles/creating-a-pull-request) for the steps to do that.

Also, to create a pull request to this repository, you'll first need to fork it.  See [github's help article on forks](https://help.github.com/articles/about-forks/) for more information.
