### ISSUE TITLE
Add more Snack examples

### ISSUE THREAD

**Issue by jesseruder** [react-community/native-directory#30]
Here are some additional examples using Snack:

react-native-gifted-chat - https://snack.expo.io/SyOdDdL8b
react-native-swiper - https://snack.expo.io/BkaD_dIL-
react-native-swipeout - https://snack.expo.io/HyQ25dU8Z
react-native-deck-swiper - https://snack.expo.io/rJBRhOLU-
react-native-material-textfield - https://snack.expo.io/SJIOAOUIb
react-native-radio-buttons - https://snack.expo.io/Bk8-1FILb
react-native-lightbox - https://snack.expo.io/rkzzeFUIW
react-native-autocomplete-input - https://snack.expo.io/rJxdeFIIb
react-native-easy-grid - https://snack.expo.io/S1QYWFILW
react-native-popup-menu - https://snack.expo.io/rkQrMFI8W
react-native-calendar-strip - https://snack.expo.io/By-aQF8LZ

**Comment by jimmylee** [comment]
thanks @jesseruder these are in now :)
