### ISSUE TITLE
Add React Native: Android App Tour Library

### ISSUE THREAD

**Issue by prscX** [react-community/native-directory#84]
Hi,

I have created a React Native bridge plugin for KeepSafe/TapTargetView. It allow users to provide App Tour. Can you please add below npm node to your React Native packages list:

Node Name: react-native-taptargetview
Link: https://github.com/prscX/react-native-taptargetview

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by jimmylee** [comment]
Responded to you here: https://github.com/react-community/native-directory/issues/87
