### ISSUE TITLE
Add React Native: iOS App Tour Library

### ISSUE THREAD

**Issue by prscX** [react-community/native-directory#87]
Hi,

I have created a React Native bridge plugin for aromajoin/material-showcase-ios. It allow users to provide App Tour. Can you please add below npm node to your React Native packages list:

Node Name: react-native-material-showcase-ios
Link: https://github.com/prscX/react-native-material-showcase-ios

Please let me know in case any discuss is required for the same

Thanks
Pranav

**Comment by jimmylee** [comment]
Hey @prscX this is pretty cool! You can submit a PR with this library, and in that PR let me know if your repository works with Expo, Web, Android and IOS.

Instructions are here: https://github.com/react-community/native-directory#how-do-i-add-a-library
